
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Utilities.Blob.BlobStorageMSI._cloudBlobClient")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.DeleteAllConfigsFromBlobStorage(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member DeleteBlobInStorageContainer does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.DeleteBlobInStorageContainer(Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer,System.String)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.DeleteBlobInStorageContainer(Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer,System.String)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member DownloadBlobStorage does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.DownloadBlobStorage(Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member GetBlobContainerReference does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.GetBlobContainerReference(System.String,System.String)~Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member GetBlobContainerReference does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.GetBlobContainerReference(System.String,System.String,System.String)~Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member ListBlobsAsync does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.ListBlobsAsync(Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{Microsoft.WindowsAzure.Storage.Blob.IListBlobItem}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.ListBlobsAsync(Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{Microsoft.WindowsAzure.Storage.Blob.IListBlobItem}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member UploadToStorageContainer does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.AzureStorageUtility.UploadToStorageContainer(Microsoft.WindowsAzure.Storage.Blob.CloudBlobContainer,System.String,System.String)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.BlobHelper.DeleteAllBlobsInAContainer(System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter blobUri of method BlobHelper.DeleteBlob(string, string) from string to System.Uri, or provide an overload to BlobHelper.DeleteBlob(string, string) that allows blobUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.BlobHelper.DeleteBlob(System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.BlobHelper.DeleteBlob(System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter blobUri of method BlobHelper.GetBlobContent(string, string) from string to System.Uri, or provide an overload to BlobHelper.GetBlobContent(string, string) that allows blobUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.BlobHelper.GetBlobContent(System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter blobUri of method BlobHelper.SaveContentToBlob(string, string, string) from string to System.Uri, or provide an overload to BlobHelper.SaveContentToBlob(string, string, string) that allows blobUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utilities.Blob.BlobHelper.SaveContentToBlob(System.String,System.String,System.String)")]
