trigger: none
variables:
- name: BuildParameters.mavenPOMFile
  value: DataProcessing/datax-core/pom.xml
- name: Codeql.Enabled
  value: true
name: $(date:yyyyMMdd)$(rev:.r)
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: Azure-Pipelines-1ESPT-ExDShared
      image: windows-2022
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Job_1
        displayName: Agent job 1
        steps:
        - checkout: self
          fetchTags: true
        - task: Maven@2
          displayName: Maven DataProcessing/datax-core/pom.xml
          inputs:
            mavenPOMFile: $(BuildParameters.mavenPOMFile)
            goals: install
            options: -e
            codeCoverageTool: JaCoCo
            mavenFeedAuthenticate: false
        - task: Maven@3
          displayName: Maven DataProcessing/datax-keyvault/pom.xml
          inputs:
            mavenPOMFile: DataProcessing/datax-keyvault/pom.xml
            goals: install
            options: -e
            testResultsFiles: '**/TEST-*.xml'
            codeCoverageTool: JaCoCo
        - task: Maven@3
          displayName: Maven DataProcessing/datax-utility/pom.xml
          inputs:
            mavenPOMFile: DataProcessing/datax-utility/pom.xml
            goals: install
            options: -e
            testResultsFiles: '**/TEST-*.xml'
            codeCoverageTool: JaCoCo
        - task: Maven@3
          displayName: Maven DataProcessing/datax-udf-samples/pom.xml
          inputs:
            mavenPOMFile: DataProcessing/datax-udf-samples/pom.xml
            goals: install
            options: -e
            testResultsFiles: '**/TEST-*.xml'
            codeCoverageTool: JaCoCo
        - task: Maven@2
          displayName: Maven DataProcessing/datax-host/pom.xml
          inputs:
            mavenPOMFile: DataProcessing/datax-host/pom.xml
            options: -e
            codeCoverageTool: JaCoCo
            mavenFeedAuthenticate: false
        - task: PublishCodeCoverageResults@1
          displayName: Publish code coverage from $(System.DefaultWorkingDirectory)/**/coverage.xml
          inputs:
            summaryFileLocation: $(System.DefaultWorkingDirectory)/**/coverage.xml