
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.ConfigSettingName_InputEventHubCheckpointDir.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.ConfigSettingName_InputEventHubCheckpointDir")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.ConfigSettingName_InputEventHubFlushExistingCheckpoints.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.ConfigSettingName_InputEventHubFlushExistingCheckpoints")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.HubType_EventHub.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.HubType_EventHub")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.HubType_IoTHub.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.HubType_IoTHub")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubCheckpointDir.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubCheckpointDir")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubCheckpointInterval.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubCheckpointInterval")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubConnectionString.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubConnectionString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubConsumerGroup.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubConsumerGroup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubFlushExistingCheckpoints.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubFlushExistingCheckpoints")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubMaxRate.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.TokenName_InputEventHubMaxRate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.HandleSensitiveData(DataX.Config.ConfigDataModel.FlowGuiConfig)~System.Threading.Tasks.Task{DataX.Config.ConfigDataModel.FlowGuiConfig}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.Process(DataX.Config.FlowDeploymentSession)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1308:In method 'Process', replace the call to 'ToLowerInvariant' with 'ToUpperInvariant'.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.Process(DataX.Config.FlowDeploymentSession)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1806:Process calls TryParse but does not explicitly check whether the conversion succeeded. Either use the return value in a conditional statement or verify that the call site expects that the out argument will be set to the default value when the conversion fails.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Input.EventHub.Processor.CreateEventHubConsumerGroup.Process(DataX.Config.FlowDeploymentSession)~System.Threading.Tasks.Task{System.String}")]
