
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.ValidateRemoteCert(System.Net.Http.HttpRequestMessage,System.Security.Cryptography.X509Certificates.X509Certificate2,System.Security.Cryptography.X509Certificates.X509Chain,System.Net.Security.SslPolicyErrors)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.IsUserInfoLoggingEnabled~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.Query(System.Net.Http.HttpRequestMessage,System.String,System.String,System.String,System.Net.Http.HttpMethod)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.MakeRequestUsingReverseProxy(DataX.Gateway.Api.Controllers.GatewayController.RequestDescriptor,Microsoft.ServiceFabric.Services.Client.ServicePartitionKey)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.Query(System.Net.Http.HttpRequestMessage,System.String,System.String,System.String,System.Net.Http.HttpMethod)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1810:Initialize reference type static fields inline", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.#cctor")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.Query(System.Net.Http.HttpRequestMessage,System.String,System.String,System.String,System.Net.Http.HttpMethod)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.QueryService(System.Net.Http.HttpRequestMessage,System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.QueryServiceWithPost(System.Net.Http.HttpRequestMessage,System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.MakeRequestUsingReverseProxy(DataX.Gateway.Api.Controllers.GatewayController.RequestDescriptor,Microsoft.ServiceFabric.Services.Client.ServicePartitionKey)~System.Threading.Tasks.Task{DataX.Contract.ApiResult}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Gateway.Api.Controllers.GatewayController.ProxyResponse(DataX.Contract.ApiResult,System.Net.Http.HttpResponseMessage)")]
