
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Utility.EventHub.EventHubInfo.Key")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Utility.EventHub.EventHubInfo.Name")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Utility.EventHub.EventHubInfo.Namespace")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Utility.EventHub.EventHubInfo.Policy")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.EventHub.EventHubManagementRestClient.CreateIotHubEndpointConsumerGroup(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2234:Modify 'EventHubManagementRestClient.CreateIotHubEndpointConsumerGroup(string, string, string, string)' to call 'HttpClient.PutAsync(Uri, HttpContent)' instead of 'HttpClient.PutAsync(string, HttpContent)'.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.EventHub.EventHubManagementRestClient.CreateIotHubEndpointConsumerGroup(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.EventHub.EventHubManagementRestClient.TryGetEventHubConsumerGroup(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{Microsoft.Azure.Management.EventHub.Models.ConsumerGroup}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.EventHub.EventHubManagementRestClient.UpsertEventHubConsumerGroup(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.EventHub.EventHubUtil.CreateEventHubConsumerGroup(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.Result}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.EventHub.EventHubUtil.CreateIotHubConsumerGroup(System.String,System.String,System.String,System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.Result}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.EventHub.EventHubUtil.UpsertHubConsumerGroup(System.String,System.String,System.String,System.String,System.String,System.String,System.String,System.Func{DataX.Utility.EventHub.EventHubManagementRestClient,System.Threading.Tasks.Task{System.Boolean}})~System.Threading.Tasks.Task{DataX.Contract.Result}")]
