
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Metrics.Ingestor.Helper.MetricItem.EventTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Metrics.Ingestor.Helper.MetricItem.MetricName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Metrics.Ingestor.Helper.MetricItem.Metric")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Metrics.Ingestor.Helper.MetricItem.Product")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Metrics.Ingestor.Helper.MetricItem.Pivot")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Metrics.Ingestor.Helper.MetricOutput.RedisKey")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Metrics.Ingestor.Helper.MetricOutput.Content")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Metrics.Ingestor.Helper.MetricOutput.EpochTime")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Helper.IngestorEventProcessor.#ctor(System.Threading.CancellationToken,StackExchange.Redis.ConnectionMultiplexer,Microsoft.Extensions.Logging.ILogger)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Helper.IngestorEventProcessor.GenerateRow(System.String)~DataX.Metrics.Ingestor.Helper.MetricOutput")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1068:CancellationToken parameters must come last", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Helper.IngestorEventProcessorFactory.#ctor(System.Threading.CancellationToken,Microsoft.Extensions.Logging.ILogger)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Helper.IngestorEventProcessor.Microsoft#Azure#EventHubs#Processor#IEventProcessor#ProcessEventsAsync(Microsoft.Azure.EventHubs.Processor.PartitionContext,System.Collections.Generic.IEnumerable{Microsoft.Azure.EventHubs.EventData})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.ServiceEventSource.Message(System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.ServiceEventSource.ServiceMessage(System.Fabric.ServiceContext,System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Helper.SecretsStore.GetMetricsEventHubListenerConnectionStringAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Helper.SecretsStore.GetMetricsRedisConnectionStringAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Helper.SecretsStore.GetMetricsStorageConnectionStringAsync~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Helper.SecretsStore.GetSecretAsync(System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Ingestor.InitalizeEventProcessorHostAsync~System.Threading.Tasks.Task{Microsoft.Azure.EventHubs.Processor.EventProcessorHost}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Ingestor.RunAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Ingestor.StartListenerAsync(Microsoft.Azure.EventHubs.Processor.EventProcessorHost,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Ingestor.StopListenerAsync(Microsoft.Azure.EventHubs.Processor.EventProcessorHost,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA1801:Review unused parameters", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Metrics.Ingestor.Ingestor.StopListenerAsync(Microsoft.Azure.EventHubs.Processor.EventProcessorHost,System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
