
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.DeleteAllBlobsInAContainer(System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter blobUri of method BlobUtility.DeleteBlob(string, string) from string to System.Uri, or provide an overload to BlobUtility.DeleteBlob(string, string) that allows blobUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.DeleteBlob(System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.DeleteBlob(System.String,System.String)~System.Threading.Tasks.Task{System.Boolean}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter blobUri of method BlobUtility.GetBlobContent(string, string) from string to System.Uri, or provide an overload to BlobUtility.GetBlobContent(string, string) that allows blobUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.GetBlobContent(System.String,System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.GetBlobContent(System.String,System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.GetBlobs(System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{System.String}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter blobUri of method BlobUtility.GetBlobs(string, string, string) from string to System.Uri, or provide an overload to BlobUtility.GetBlobs(string, string, string) that allows blobUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.GetBlobs(System.String,System.String,System.String)~System.Threading.Tasks.Task{System.Collections.Generic.List{System.String}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.ReadFromBlob(Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter blobUri of method BlobUtility.SaveContentToBlob(string, string, string) from string to System.Uri, or provide an overload to BlobUtility.SaveContentToBlob(string, string, string) that allows blobUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.SaveContentToBlob(System.String,System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.Blob.BlobUtility.SaveContentToBlob(System.String,System.String,System.String)~System.Threading.Tasks.Task")]
