
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.KeyVaultUtility.DeleteSecretAsync(System.String,System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member GetKeyVaultSecretUrl does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.KeyVaultUtility.GetKeyVaultSecretUrl(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter secretUri of method KeyVaultUtility.GetSecretFromKeyvaultAsync(string) from string to System.Uri, or provide an overload to KeyVaultUtility.GetSecretFromKeyvaultAsync(string) that allows secretUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.KeyVaultUtility.GetSecretFromKeyvaultAsync(System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.KeyVaultUtility.GetSecretFromKeyvaultAsync(System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.KeyVaultUtility.GetSecretStringAsync(System.String,System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.KeyVaultUtility.SaveSecretStringAsync(System.String,System.String,System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1055:Change the return type of method SecretUriParser.ComposeUri(string, string) from string to System.Uri.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.SecretUriParser.ComposeUri(System.String,System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter secretUri of method SecretUriParser.ParseSecretUri(string, out string, out string) from string to System.Uri, or provide an overload to SecretUriParser.ParseSecretUri(string, out string, out string) that allows secretUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.SecretUriParser.ParseSecretUri(System.String,System.String@,System.String@)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter secretUri of method SecretUriParser.TryParseSecretUri(string, out string, out string) from string to System.Uri, or provide an overload to SecretUriParser.TryParseSecretUri(string, out string, out string) that allows secretUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Utility.KeyVault.SecretUriParser.TryParseSecretUri(System.String,System.String@,System.String@)~System.Boolean")]
