
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGenService.GetDataSchemaAndRules(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.SimulatedData.DataGenService.Model.DataSchema}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGenService.RunAsync(System.Threading.CancellationToken)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGenService.SendData(System.String,System.String,System.Collections.Generic.List{Newtonsoft.Json.Linq.JObject})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGenService.SendToEventHubBatch(System.String,System.Collections.Generic.List{Newtonsoft.Json.Linq.JObject})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "CA2007:Do not directly await a Task", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGenService.SendToIotHubBatch(System.String,System.Collections.Generic.List{Newtonsoft.Json.Linq.JObject})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.SimulatedData.DataGenService.Model.DataObject.fields")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.SimulatedData.DataGenService.Model.DataObject.rulesData")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.SimulatedData.DataGenService.Model.DataSchema.dataSchema")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.SimulatedData.DataGenService.Model.Field.properties")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.SimulatedData.DataGenService.Model.Properties.properties")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.SimulatedData.DataGenService.Model.Properties.valueList")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.SimulatedData.DataGenService.Model.RulesData.triggerConditions")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CA2227:Collection properties should be read only", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.SimulatedData.DataGenService.Model.TriggerConditions.ruleNotTriggerTimeInMinutes")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GeneratePropertyString(System.Collections.Generic.List{DataX.SimulatedData.DataGenService.Model.Properties})~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GenerateRulesData(DataX.SimulatedData.DataGenService.Model.RulesData,System.Int32)~Newtonsoft.Json.Linq.JObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGenService.SendToIotHubBatch(System.String,System.Collections.Generic.List{Newtonsoft.Json.Linq.JObject})~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0047:Remove unnecessary parentheses", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GeneratePropertyString(System.Collections.Generic.List{DataX.SimulatedData.DataGenService.Model.Properties})~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0047:Remove unnecessary parentheses", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GenerateRandomData(System.Collections.Generic.List{Newtonsoft.Json.Linq.JObject},DataX.SimulatedData.DataGenService.Model.DataObject)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0047:Remove unnecessary parentheses", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GenerateRulesData(DataX.SimulatedData.DataGenService.Model.RulesData,System.Int32)~Newtonsoft.Json.Linq.JObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "IDE0048:Add parentheses for clarity", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GetRandomDouble(System.Double,System.Double)~System.Double")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.ServiceEventSource.Message(System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1305:Specify IFormatProvider", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.ServiceEventSource.ServiceMessage(System.Fabric.StatelessServiceContext,System.String,System.Object[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GeneratePropertyString(System.Collections.Generic.List{DataX.SimulatedData.DataGenService.Model.Properties})~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GenerateRandomData(System.Collections.Generic.List{Newtonsoft.Json.Linq.JObject},DataX.SimulatedData.DataGenService.Model.DataObject)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGen.GenerateRulesData(DataX.SimulatedData.DataGenService.Model.RulesData,System.Int32)~Newtonsoft.Json.Linq.JObject")]

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "CA1822:Mark members as static", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.SimulatedData.DataGenService.DataGenService.SendToEventHubBatch(System.String,System.Collections.Generic.List{Newtonsoft.Json.Linq.JObject})~System.Threading.Tasks.Task")]
