
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubCheckpointDir.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubCheckpointDir")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubCheckpointInterval.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubCheckpointInterval")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubConnectionString.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubConnectionString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubConsumerGroup.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubConsumerGroup")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubFlushExistingCheckpoints.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubFlushExistingCheckpoints")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubMaxRate.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Test.Config.Processor.EventHubInputConfigGenProcessor.TokenName_InputEventHubMaxRate")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1051:Do not declare visible instance fields", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Test.Mock.RuntimeStorage.Cache")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter tc of method Initialize is never used. Remove the parameter or use it in the method body.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.CompositionTest.Initialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Extension.CommonDataExtension.Add(DataX.Config.ICommonDataManager,System.String,System.String)~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.FlattenerTest.TestFlatten~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter tc of method Initialize is never used. Remove the parameter or use it in the method body.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.FlowOperationTest.Initialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.FlowOperationTest.TestConfigSaved~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter tc of method Initialize is never used. Remove the parameter or use it in the method body.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.LoggerTest.Initialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Mock.DesignTimeStorage.DeleteByName(System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.Result}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Mock.DesignTimeStorage.GetAll(System.String)~System.Threading.Tasks.Task{System.String[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Mock.DesignTimeStorage.GetByNames(System.String[],System.String)~System.Threading.Tasks.Task{System.String[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Mock.DesignTimeStorage.SaveByName(System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.Result}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Mock.DesignTimeStorage.UpdatePartialByName(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.Result}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Mock.KeyVaultClient.GetSecretFromKeyVaultAsync(System.String,System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1054:Change the type of parameter secretUri of method KeyVaultClient.ResolveSecretUriAsync(string) from string to System.Uri, or provide an overload to KeyVaultClient.ResolveSecretUriAsync(string) that allows secretUri to be passed as a System.Uri object.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Mock.KeyVaultClient.ResolveSecretUriAsync(System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1307:The behavior of 'string.Contains(string)' could vary based on the current user's locale settings. Replace this call in 'DataX.Config.Test.Mock.RuntimeStorage.Delete(string)' with a call to 'string.Contains(string, System.StringComparison)'.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.Mock.RuntimeStorage.Delete(System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1801:Parameter tc of method Initialize is never used. Remove the parameter or use it in the method body.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.RuntimeConfigGenerationTest.Initialize(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.RuntimeConfigGenerationTest.TestEndToEndGeneration~System.Threading.Tasks.Task")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Test.RuntimeConfigGenerationTest.VerifyJsonConfigGenerated.Process(DataX.Config.FlowDeploymentSession)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'GeneralObject' to be read-only by removing the property setter.", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.Config.Test.JsonConverterTest.TestType.GeneralObject")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2227:Change 'Map' to be read-only by removing the property setter.", Justification = "Critical issues only", Scope = "member", Target = "~P:DataX.Config.Test.JsonConverterTest.TestType.Map")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1710:Rename DataX.Config.Test.Mock.ConfigurationProvider to end in 'Dictionary'.", Justification = "Critical issues only", Scope = "type", Target = "~T:DataX.Config.Test.Mock.ConfigurationProvider")]
