
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Storage.AzureBlobConfigStorage.ConfigSettingName_RuntimeStorageConnectionString.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Storage.AzureBlobConfigStorage.ConfigSettingName_RuntimeStorageConnectionString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Storage.CosmosDBConfigStorage.ConfigSettingName_DesignTimeCosmosDBConnectionString.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Storage.CosmosDBConfigStorage.ConfigSettingName_DesignTimeCosmosDBConnectionString")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1707:Remove the underscores from member name DataX.Config.Storage.CosmosDBConfigStorage.ConfigSettingName_DesignTimeCosmosDBDatabaseName.", Justification = "Critical issues only", Scope = "member", Target = "~F:DataX.Config.Storage.CosmosDBConfigStorage.ConfigSettingName_DesignTimeCosmosDBDatabaseName")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.AzureBlobConfigStorage.Delete(System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1822:Member NormalizeFilePath does not access instance data and can be marked as static (Shared in VisualBasic)", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.AzureBlobConfigStorage.NormalizeFilePath(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA1304:The behavior of 'string.ToLower()' could vary based on the current user's locale settings. Replace this call in 'AzureBlobConfigStorage.NormalizeFilePath(string)' with a call to 'string.ToLower(CultureInfo)'.", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.AzureBlobConfigStorage.NormalizeFilePath(System.String)~System.String")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.AzureBlobConfigStorage.SaveFile(System.String,System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.CosmosDBConfigStorage.DeleteByName(System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.Result}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.CosmosDBConfigStorage.GetAll(System.String)~System.Threading.Tasks.Task{System.String[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.CosmosDBConfigStorage.GetByFieldValue(System.String,System.String,System.String)~System.Threading.Tasks.Task{System.String[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.CosmosDBConfigStorage.GetByName(System.String,System.String)~System.Threading.Tasks.Task{System.String}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.CosmosDBConfigStorage.GetByNames(System.String[],System.String)~System.Threading.Tasks.Task{System.String[]}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.CosmosDBConfigStorage.SaveByName(System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.Result}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Build", "CA2007:Do not directly await a Task without calling ConfigureAwait", Justification = "Critical issues only", Scope = "member", Target = "~M:DataX.Config.Storage.CosmosDBConfigStorage.UpdatePartialByName(System.String,System.String,System.String,System.String)~System.Threading.Tasks.Task{DataX.Contract.Result}")]
